### ISSUE TITLE
cmake のパラメータについて

### ISSUE THREAD

**Issue by sorakoro** [kujirahand/raspi_opencv_install#2]
`-D ENABLE_PRECOMPILED_HEADERS=OFF` を付与したほうがいいかも？しれないです。

自分の環境では `fatal error: stdlib.h: No such file or directory` が出てコンパイルが強制終了してしまいました。

**Comment by kujirahand** [comment]
すみません。こちら今頃気付きました。
ご指摘ありがとうございます！

既にOpenCV4.1がaptでインストールできるようになっていますね。
aptでインストールする方法で変更させていただきました。
一度、閉じさせていただきます。
